name: ci_mac

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_mac.yml"

jobs:

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install autoconf automake libtool

    - run: cmake -B build
      # autotools needs these full variables
      env:
        CC: /usr/local/bin/gcc-10
        FC: /usr/local/bin/gfortran-10
        F77: /usr/local/bin/gfortran-10

    - run: cmake --build build
