name: ci_mac

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_mac.yml"

jobs:

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install autoconf automake

    # devel test bug for MacOS
    - run: cmake -B build -DBUILD_TESTING:BOOL=false --log-level=VERBOSE

    - run: cmake --build build
